In [3]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

This code will print out the data types of both list_ and array_list, and you can compare them to see if there is any difference. Typically, list_ will have a data type of list, and array_list will have a data type like numpy.ndarray.






In [37]:
import numpy as np

# Create a Python list
list_ = ['1', '2', '3', '4', '5']

# Create a NumPy array from the list
array_list = np.array(list_)

# Check the data types of both variables
print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))


Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [38]:
array_list.dtype

dtype('<U1')

In [39]:
for item in list_:
    dt = type(item)
    print(dt)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [40]:
array_list = np.array(object = list_, dtype = int)

In [41]:
array_list

array([1, 2, 3, 4, 5])

In [42]:
array_list.dtype

dtype('int64')

In [43]:
for item in list_:
    dt = type(item)
    print(dt)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [44]:
list2 = [1,2.3,4.6,6,7,8]

In [20]:
array_list = np.array(object = list2, dtype = int)

In [45]:
array_list 

array([1, 2, 3, 4, 5])

In [46]:
for item in list2:
    dt = type(item)
    print(dt)

<class 'int'>
<class 'float'>
<class 'float'>
<class 'int'>
<class 'int'>
<class 'int'>


In above two examples we can see array_list contains only integer datatype in list_ ,but when we check datatype of
list_ and list2 datatype remains same.

Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [47]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [48]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
num_array.size

6

In [27]:
num_array.shape

(2, 3)

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [34]:
m1 = np.array([1,1,1,1,1])

In [35]:
m1

array([1, 1, 1, 1, 1])

In [36]:
np.diag(m1)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])